sudo: false
install: true
language: android
dist: trusty
group: edge
jdk: oraclejdk8
branches:
  only:
    - master
    - develop

android:
  components:
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-26

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
    - intel-android-extra-license.+

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_script:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-28"

script:
  - ./gradlew assembleRelease --stacktrace